"use client";
import { useState, useEffect } from "react";
import { useCart } from "@/context/CartContext";
import { useAuth } from "@/context/AuthContext";
import { useRouter } from "next/navigation";
import Script from "next/script";

export default function CheckoutPage() {
  const { cartItems, totalPrice, isLoaded } = useCart();
  const { user, session, loading: authLoading, openAuthModal } = useAuth();
  const router = useRouter();

  const [formData, setFormData] = useState({ name: '', email: '', mobile: '', address: '', pincode: '' });

  // Pre-fill email and name if available
  useEffect(() => {
    if (user) {
      setFormData(prev => ({
        ...prev,
        email: user.email || '',
        name: user.user_metadata?.full_name || ''
      }));
    }
  }, [user]);

  // Protect route
  useEffect(() => {
    if (!authLoading && !user) {
      openAuthModal();
      router.push('/cart');
    }
  }, [user, authLoading, router, openAuthModal]);

  const handleMobileChange = (e) => {
    let val = e.target.value.replace(/\D/g, ''); // Remove non-digits
    
    // Automatically strip leading zero if user pastes an 11-digit number starting with 0
    if (val.length > 10 && val.startsWith('0')) {
      val = val.substring(1);
    }
    // Also handle trailing zero bug just in case they added one by mistake at the end of 10 digits
    else if (val.length > 10 && val.endsWith('0')) {
      val = val.substring(0, 10);
    }
    
    // Limit to 10 digits maximum anyway
    if (val.length > 10) val = val.substring(0, 10);
    
    setFormData({...formData, mobile: val});
  };

  const handlePay = async (e) => {
    e.preventDefault();
    if(cartItems.length === 0) return;
    
    // Check if Razorpay is loaded
    if (typeof window === "undefined" || !window.Razorpay) {
      alert("Razorpay SDK failed to load. Are you online?");
      return;
    }

    try {
      // 1. Send the order details to our new FastAPI Backend using env variable
      const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
      const response = await fetch(`${API_URL}/api/v1/orders/`, {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
          "Authorization": session ? `Bearer ${session.access_token}` : ""
        },
        body: JSON.stringify({
          customer_name: formData.name,
          customer_email: formData.email,
          customer_mobile: formData.mobile,
          customer_address: formData.address,
          customer_pincode: formData.pincode,
          items: cartItems.map(i => ({
             id: i.id, name: i.name, size: i.size, price: i.price, quantity: i.quantity
          })),
          total_amount: totalPrice
        })
      });

      if (!response.ok) {
        throw new Error("Failed to create order on server");
      }

      const backendOrder = await response.json();

      // 2. Open Razorpay using the official secure order_id from our backend
      const options = {
        key: "rzp_test_SowtC06Uh2Hzs4", // Your live test key
        amount: totalPrice * 100, 
        currency: "INR",
        name: "HUNKX",
        description: "Secure Order",
        image: "https://placehold.co/150x150/0a0805/d4a23a?text=HUNKX",
        order_id: backendOrder.razorpay_order_id, // Secure order ID generated by backend!
        handler: function (response) {
          // Success! In the next step, we will verify this signature on the backend.
          // For now, save the successful order details and redirect.
          const orderData = {
            id: backendOrder.id,
            total: totalPrice,
            customer: formData,
            items: cartItems,
            payment_id: response.razorpay_payment_id
          };
          localStorage.setItem("hunkx_pending_order", JSON.stringify(orderData));
          router.push("/success");
        },
        prefill: {
          name: formData.name,
          contact: formData.mobile,
        },
        theme: {
          color: "#d4a23a" // Matching our gold aesthetic
        }
      };

      const rzp = new window.Razorpay(options);
      
      rzp.on('payment.failed', function (response){
        alert("Payment Failed! Reason: " + response.error.description);
      });
      
      rzp.open();
    } catch (err) {
      alert("Error processing order: " + err.message);
    }
  };

  if (!isLoaded || authLoading || !user) return null;

  return (
    <main style={{ paddingTop: '120px', minHeight: '100vh', paddingBottom: '60px', paddingLeft: '5%', paddingRight: '5%' }}>
      {/* Load Razorpay Script securely via Next.js */}
      <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" />
      
      <button onClick={() => router.back()} style={{ background: 'transparent', border: 'none', color: 'var(--gold)', cursor: 'pointer', marginBottom: '30px', fontSize: '1rem', fontFamily: 'Cinzel, serif' }}>
        ← Back
      </button>

      <section style={{ maxWidth: '800px', margin: '0 auto' }}>
        <h1 className="section-title" style={{ textAlign: 'center', marginBottom: '40px' }}>Secure <span>Checkout</span></h1>
        
        <form onSubmit={handlePay} style={{ display: 'grid', gap: '20px' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: 'var(--gold)' }}>Full Name</label>
            <input required type="text" placeholder="John Doe" value={formData.name} onChange={e=>setFormData({...formData, name: e.target.value})} style={{ width: '100%', padding: '15px', background: 'var(--black-soft)', border: '1px solid rgba(212,162,58,0.3)', color: 'white', fontFamily: 'Inter' }} />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: 'var(--gold)' }}>Email Address</label>
            <input required type="email" placeholder="you@example.com" value={formData.email} onChange={e=>setFormData({...formData, email: e.target.value})} style={{ width: '100%', padding: '15px', background: 'var(--black-soft)', border: '1px solid rgba(212,162,58,0.3)', color: 'white', fontFamily: 'Inter' }} />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: 'var(--gold)' }}>Mobile Number</label>
            <input required pattern="[0-9]{10}" title="10 digit mobile number" placeholder="9876543210" type="tel" value={formData.mobile} onChange={handleMobileChange} style={{ width: '100%', padding: '15px', background: 'var(--black-soft)', border: '1px solid rgba(212,162,58,0.3)', color: 'white', fontFamily: 'Inter' }} />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: 'var(--gold)' }}>Delivery Address</label>
            <textarea required rows="3" placeholder="Flat No, Building, Street..." onChange={e=>setFormData({...formData, address: e.target.value})} style={{ width: '100%', padding: '15px', background: 'var(--black-soft)', border: '1px solid rgba(212,162,58,0.3)', color: 'white', fontFamily: 'Inter' }} />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', color: 'var(--gold)' }}>Pincode</label>
            <input required pattern="[0-9]{6}" title="6 digit pincode" placeholder="201005" type="text" onChange={e=>setFormData({...formData, pincode: e.target.value})} style={{ width: '100%', padding: '15px', background: 'var(--black-soft)', border: '1px solid rgba(212,162,58,0.3)', color: 'white', fontFamily: 'Inter' }} />
          </div>

          <div style={{ marginTop: '20px', padding: '20px', border: '1px solid var(--gold)', background: 'var(--black-soft)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '1.2rem', fontWeight: 'bold' }}>
              <span>Total Amount to Pay:</span>
              <span style={{ color: 'var(--gold-bright)' }}>₹{totalPrice}</span>
            </div>
          </div>

          <button type="submit" className="btn-primary" style={{ marginTop: '20px', fontSize: '1.2rem', padding: '20px' }}>
            Pay ₹{totalPrice} Securely
          </button>
        </form>
      </section>
    </main>
  );
}
